<a href="https://colab.research.google.com/github/Bossism/DailyStudy/blob/master/datawhalechina_hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 创建tensor

In [1]:
import torch

In [2]:
x = torch.rand(4, 3)
x

tensor([[0.6767, 0.8286, 0.3790],
        [0.6837, 0.1233, 0.2980],
        [0.6336, 0.8101, 0.0954],
        [0.5896, 0.6531, 0.8740]])

In [3]:
x = torch.zeros(4, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [5]:
x = x.new_ones(4, 3, dtype=torch.float)
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.0927,  0.7754, -0.1235],
        [ 2.8375,  0.4702, -0.9763],
        [-1.1091, -1.0981,  1.1401],
        [-1.7541, -0.0968, -0.3775]])

In [6]:
x.size()

torch.Size([4, 3])

In [7]:
x.shape

torch.Size([4, 3])

### 一些操作

In [8]:
y = torch.rand(4, 3)
x + y

tensor([[ 0.3257,  1.4568, -0.0687],
        [ 2.8470,  0.8031, -0.0869],
        [-1.0918, -0.7266,  1.3238],
        [-1.4431,  0.3000,  0.4827]])

In [9]:
torch.add(x, y)

tensor([[ 0.3257,  1.4568, -0.0687],
        [ 2.8470,  0.8031, -0.0869],
        [-1.0918, -0.7266,  1.3238],
        [-1.4431,  0.3000,  0.4827]])

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: An output with one or more elements was resized since it had shape [5, 3], which does not match the required output shape [4, 3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:23.)
  


tensor([[ 0.3257,  1.4568, -0.0687],
        [ 2.8470,  0.8031, -0.0869],
        [-1.0918, -0.7266,  1.3238],
        [-1.4431,  0.3000,  0.4827]])

In [11]:
y.add_(x)
y

tensor([[ 0.3257,  1.4568, -0.0687],
        [ 2.8470,  0.8031, -0.0869],
        [-1.0918, -0.7266,  1.3238],
        [-1.4431,  0.3000,  0.4827]])

In [12]:
x[:, 1]

tensor([ 0.7754,  0.4702, -1.0981, -0.0968])

In [13]:
y = x[0, :]
y += 1
print(y)
print(x[0, :])

tensor([0.9073, 1.7754, 0.8765])
tensor([0.9073, 1.7754, 0.8765])


注意 view() 返回的新tensor与源tensor共享内存(其实是同一个tensor)，也即更改其中的一个，另 外一个也会跟着改变。

In [15]:
x = torch.randn(4, 4)
y = x.view(-1, 8)
y.size()

torch.Size([2, 8])

所以如果我们想返回一个真正新的副本(即不共享内存)该怎么办呢？Pytorch还提供了一 个 reshape() 可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用 clone 创造一个副本然后再使用 view 。

注意：使用 clone 还有一个好处是会被记录在计算图中，即梯度回传到副本时也会传到源 Tensor 。

如果你有一个元素 tensor ，使用 .item() 来获得这个 value：

In [16]:
x = torch.randn(1)
x.item

<function Tensor.item>

广播机制

In [19]:
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(1, 4).view(3, 1)
x + y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

### 自动求导

In [20]:
import torch
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [21]:
y = x ** 2
y

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)

In [22]:
y.grad_fn

In [23]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>) tensor(3., grad_fn=<MeanBackward0>)


In [25]:
out.backward()

In [24]:
a = torch.randn(2, 2) # 缺失情况下默认 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [26]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
i = 0
while y.data.norm() < 1000:
    y = y * 2
    i = i + 1
print(y)
print(i)

tensor([-0.2133, -1.3176,  0.9632], requires_grad=True)
tensor([ -218.4471, -1349.2706,   986.3589], grad_fn=<MulBackward0>)
9


In [27]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [28]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [29]:
x = torch.ones(1,requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值 
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
